MMDVMDNPC = MMDVMDNPC or {}

if SERVER then
    AddCSLuaFile("mmd_vmd_npc/sh_core.lua")
    AddCSLuaFile("mmd_vmd_npc/cl_menu.lua")

    util.AddNetworkString("mmdvmd_list_request")
    util.AddNetworkString("mmdvmd_list_response")
    util.AddNetworkString("mmdvmd_motion_details_request")
    util.AddNetworkString("mmdvmd_motion_details_response")
    util.AddNetworkString("mmdvmd_pause_status_request")
    util.AddNetworkString("mmdvmd_pause_status_response")
    util.AddNetworkString("mmdvmd_debug_request")
    util.AddNetworkString("mmdvmd_debug_response")
    util.AddNetworkString("mmdvmd_debug_open")
    util.AddNetworkString("mmdvmd_debug_apply")
    util.AddNetworkString("mmdvmd_flex_override_save")
    util.AddNetworkString("mmdvmd_flex_override_clear")
    util.AddNetworkString("mmdvmd_flex_override_unassign")
    util.AddNetworkString("mmdvmd_select_target")
    util.AddNetworkString("mmdvmd_target_status")
    util.AddNetworkString("mmdvmd_assignment_status")
    util.AddNetworkString("mmdvmd_assignment_play_request")
    util.AddNetworkString("mmdvmd_assignment_clear_request")
    util.AddNetworkString("mmdvmd_assignment_align_request")
    util.AddNetworkString("mmdvmd_build_begin")
    util.AddNetworkString("mmdvmd_build_plan")
    util.AddNetworkString("mmdvmd_build_compact_request")
    util.AddNetworkString("mmdvmd_build_frame_request")
    util.AddNetworkString("mmdvmd_build_frame_result")
    util.AddNetworkString("mmdvmd_build_done")
    util.AddNetworkString("mmdvmd_build_progress")
    util.AddNetworkString("mmdvmd_build_cancel_request")
    util.AddNetworkString("mmdvmd_play_request")
    util.AddNetworkString("mmdvmd_stop_request")
    util.AddNetworkString("mmdvmd_stop_npc_playbacks_request")
    util.AddNetworkString("mmdvmd_force_self_reset_request")
    util.AddNetworkString("mmdvmd_play_status")
    util.AddNetworkString("mmdvmd_clear_built_request")
    util.AddNetworkString("mmdvmd_clear_built_done")
    util.AddNetworkString("mmdvmd_delete_motion_request")
    util.AddNetworkString("mmdvmd_delete_motion_done")
    util.AddNetworkString("mmdvmd_audio_settings_request")
    util.AddNetworkString("mmdvmd_audio_settings_response")
    util.AddNetworkString("mmdvmd_audio_settings_save")
    util.AddNetworkString("mmdvmd_audio_start")
    util.AddNetworkString("mmdvmd_audio_stop")
    util.AddNetworkString("mmdvmd_audio_pause")
    util.AddNetworkString("mmdvmd_eye_track_camera")
end

include("mmd_vmd_npc/sh_core.lua")

if SERVER then
    include("mmd_vmd_npc/sv_cache.lua")
    include("mmd_vmd_npc/sv_commands.lua")
else
    include("mmd_vmd_npc/cl_menu.lua")
end
